package com.school.sba.requestdto;

import java.time.LocalDate;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class AcademicProgramRequest {

//	@NotNull(message = "program type should not be null")
//	@NotBlank(message = "program type should not be blank")
	private String programType;
	
//	@NotNull(message = "program name should not be null")
//	@NotBlank(message = "program name should not be blank")
	private String programName;
	
//	@NotNull(message = "program begin time should not be null")
//	@NotBlank(message = "program begin time should not be blank, it should be in the format of 'YYYY-MM-DD'")
	private LocalDate programBeginsAt;
	
//	@NotNull(message = "program end time should not be null")
//	@NotBlank(message = "program end time should not be kept blank, it should be in the format of 'YYYY-MM-DD'")
	private LocalDate programEndsAt;
	
//	@NotEmpty(message = "auto generation should either be true or false")
	private boolean autoGeneratedClassHour;
	
}
